			-- Exploratory Data Analysis Mysql project
            
	#1 Count How Many Customers You Have
SELECT COUNT(*) AS total_customers
FROM customers;

	#2 List All Products With Their Prices
SELECT product_name, price
FROM products;

	#3 Count Orders Made in Each City
SELECT 
    c.city,
    COUNT(o.order_id) AS orders_in_city
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.city;

	#4 Find Total Quantity Sold for Each Product
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC;

	#5 Show All Orders With Customer Names
SELECT 
    o.order_id,
    c.customer_name,
    o.order_date
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
ORDER BY o.order_date;

	#6 Total Revenue per Order
SELECT 
    o.order_id,
    SUM(oi.quantity * p.price) AS order_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY o.order_id
ORDER BY order_revenue DESC;

	#7 Number of Customers in Each City
SELECT 
    city,
    COUNT(*) AS total_customers
FROM customers
GROUP BY city
ORDER BY total_customers DESC;

	#8 List Products by Category
SELECT 
    category,
    product_name,
    price
FROM products
ORDER BY category, price;

	#9 Daily Order Count
SELECT 
    order_date,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY order_date;

	#10 Simple Category Revenue
SELECT 
    p.category,
    SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category;

	#11 Customers Who Placed More Than 1 Order
SELECT 
    customer_id,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
HAVING total_orders > 1;

	#12 Show Orders Paid by UPI
    SELECT *
FROM orders
WHERE payment_method = 'UPI';

	#13 Find the Most Expensive Product
SELECT *
FROM products
ORDER BY price DESC
LIMIT 1;

 #14 Find the Cheapest Product
SELECT *
FROM products
ORDER BY price ASC
LIMIT 1;

	#15 Show Customers Who Live in Mumbai
SELECT customer_name
FROM customers
WHERE city = 'Mumbai';

	#16 Find Revenue Generated by Each Customer
    SELECT 
    c.customer_name,
    SUM(oi.quantity * p.price) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_revenue DESC;

	#17 Count How Many Products Each Category Has
SELECT 
    category,
    COUNT(product_id) AS total_products
FROM products
GROUP BY category;

	#18 List All Orders With Payment Method
SELECT 
    order_id,
    order_date,
    payment_method
FROM orders
ORDER BY order_date;

	#19 Show Average Age of Customers in Each City
SELECT 
    city,
    AVG(age) AS avg_age
FROM customers
GROUP BY city
ORDER BY avg_age;

    #20 Find Products Priced Above the Category Average
SELECT 
    p.product_name,
    p.category,
    p.price
FROM products p
WHERE p.price > (
    SELECT AVG(price) 
    FROM products 
    WHERE category = p.category
);
